name:                Ex2-Adder
version:             0.1.0.0
github:              "shmuelhanoch/Ex2-Adder"
license:             BSD3
author:              "Shmuel Hanoch"
maintainer:          "shmuelhanoch@gmail.com"
copyright:           "2020 Shmuel Hanoch"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/shmuelhanoch/Ex2-Adder#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- megaparsec
- text

library:
  source-dirs: src

executables:
  Ex2-Adder-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Ex2-Adder

tests:
  Ex2-Adder-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Ex2-Adder

  Ex2-Adder-test:
    main:                ParserSpec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Ex2-Adder
    - hspec
